language: python

python:
   - "3.5"

before-install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install pylint
    - pip install flask 
    - pip install flask_sqlalchemy
    - pip install flask_script

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
