FORMAT: 1A
HOST: http://opensourcery.me/

# OPENSOURCERY API
API for http://opensourcery.me

## Project [/projects/{id}]
Represents a single project.

Required attributes: 

- `id`              The unique ID of the Project
- `name`            The name of the Project
- `github_url`      The url of the Project on GitHub
- `languages`       A list of languages used in the Project
- `contributors`    A list of contributors of the Project
- `description`     A description of the Projecthttp://docs.opensorcery.apiary.io/traffic

+ Parameters
    + id (required, integer) ... Unique ID

+ Model (application/json)

    + Body

            {
                "id" : 10,
                "name": "Example Project",
                "url" : "http://github.com/example_projct",
                "languages" : ["JavaScript", "Python"],
                "contributors": ["user1", "user2"],
                "owner": "Google"
            }
            
## Retrieve a single Project [GET]

+ Response 200

    [Project][]
    
+ Response 404 (application/json)

        "Resource not found" 


# Project List [/projects]
Get all projects.

+ Model (application/json)

    + Body

            [
                {
                    "id": 10,
                    "name": "Example Project1",
                    "github_url" : "http://github.com/example_project1"
                    "language" : ["Javascipt", "Python"],
                    "contributors": ["user1", "user2"],
                    "owner": "Google"
                },
                {
                    "id": 2,
                    "name": "Example Project2",
                    "github_url" : "http://github.com/example_project2"
                    "languages" : ["Java"],
                    "contributors": ["user1", "user2"],
                    "owner": "Microsoft"
                }
            ]
            

## List all projects [GET]

+ Response 200

    [Project List][]

## Company [/companies/{name}]
Represents a single company.

Required attributes: 

- `name`            The name of the company
- `projects`        A list of projects ids owned by the Company
- `members`         A list of contributors ids that belong to this company
- `description`     A description of the company

+ Parameters
    + name (required, string) ... Unique name

+ Model (application/json)

    + Body

            {
                "name": "Google",
                "url" : "http://github.com/google",
                "project_ids": [10, 12],
                "member_ids": [3, 4],
                "description": "Google is a a company focused on ..."
            }
            
## Retrieve a single Company [GET]

+ Response 200

    [Company][]
    
+ Response 404 (application/json)

        "Resource not found" 


# Company List [/companies]
Get all companies.

+ Model (application/json)

    + Body

            [
                {
                    "name": "Google",
                    "github_url" : "http://github.com/google",
                    "projects": ["project1", "project2"],
                    "description": "Google is a a company focused on ..."
                },
                {
                    "name": "Microsoft",
                    "github_url" : "http://github.com/microsoft",
                    "projects": ["project2", "project20"],
                    "description": "Microsoft is a company focused on ..."
                }
            ]
            

## List all companies [GET]

+ Response 200

    [Company List][]

## Contributor [/contributors/{username}]
Represents a single contributor.

Required attributes: 

- `username`  The username of the contributor
- `email`     The email address of the contributor
- `projects`  A list of projects this contributor contributed to

+ Parameters
    + username (required, string) ... Unique username

+ Model (application/json)

    + Body

            {
                "id": 2,
                "username": "example_name",
                "email": "example@example.com",
                "github_url": http://github.com/user1,
                "projects": ["project1", "project2"],
                "companies": ["Google", "Microsoft"]
            }
            
## Retrieve a single Contributor [GET]

+ Response 200

    [Contributor][]
    
+ Response 404 (application/json)

        "Resource not found" 


# Contributor List [/contributors]
Get all contributors.

+ Model (application/json)

    + Body

            [
                {
                    "id": 2,
                    "username": "user1",
                    "email": "user1@example.com",
                    "github_url": http://github.com/user1,
                    "projects": ["project1", "project2"]
                },
                {
                    "id": 4,
                    "username": "user2",
                    "email": "user2@example.com",
                    "github_url": http://github.com/user1,
                    "projects": ["project2", "project8"]
                }
            ]
            

## List all Contributors [GET]

+ Response 200

    [Contributor List][]

## Language [/languages/{name}]
Represents a single language.

Required attributes: 

- `name`            The name of the language
- `creator`         The creator of the language
- `description`     A description of the language
- `projects`        A list of projects that use this language

+ Parameters
    + name (required, string) ... Unique name

+ Model (application/json)

    + Body

            {
                "name": "Python",
                "creator": "Guido van Rossum",
                "projects" ["project1","project2"],
                "description": "Python is scripting language for ...",
                "paradigm" : [functional, object oriented]
            }
            
## Retrieve a single Language [GET]

+ Response 200

    [Language][]
    
+ Response 404 (application/json)

        "Resource not found" 


# Language List [/languages]
Get all languages.

+ Model (application/json)

    + Body

            [
                {
                    "name": "Python",
                    "creator": "Guido van Rossum",
                    "projects": ["project1","project2"],
                    "description": "Python is a programming language for ..."
                },
                {
                    "name": "Java",
                    "creator": "James Gosling",
                    "projects": ["project4","project10"],
                    "description": "Java is a programming language for ..."
                }
            ]
            

## List all Languages [GET]

+ Response 200

    [Language List][]